#ifndef _VERSION_H_
#define _VERSION_H_

#include "build_number.h"

#define VERSION_MAJOR 0
#define VERSION_MINOR 0
#define VERSION_PATCH 1

#define VERSION_STRINGISE(x) #x
#define VERSION_TO_STR(x) VERSION_STRINGISE(x)

#define VERSION_STRING "OpenBGI " VERSION_TO_STR(VERSION_MAJOR) "." VERSION_TO_STR(VERSION_MINOR) "." VERSION_TO_STR(VERSION_PATCH) " Build " VERSION_TO_STR(BUILD_NUMBER)

#endif